# Generated by Django 4.2.7 on 2026-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_summary', 'Nouveau résumé'), ('summary_validated', 'Résumé validé'), ('summary_created', 'Résumé créé (CP)'), ('new_exercise', 'Nouvel exercice'), ('system', 'Système'), ('promo', 'Promotion'), ('payment', 'Paiement'), ('general', 'Général')], default='general', max_length=30),
        ),
    ]
