workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: resumeplus
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            "com.example.resumeplus.resumePlusClean" \
            --type IOS_APP_STORE \
            --create
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true