workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: resumeplus  # Doit correspondre au nom que vous avez donné lors de la configuration de la clé API dans Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.resumeplus.resumePlusClean  # Remplacez par le Bundle ID que vous avez créé sur Apple, identique à celui de votre projet
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testeurs_internes  # Le nom du groupe de testeurs dans TestFlight, à confirmer dans App Store Connect