# Generated by Django 4.2.7 on 2025-08-27 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_service_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_abonnements', to=settings.AUTH_USER_MODEL),
        ),
    ]
