# Generated by Django 4.2.7 on 2025-11-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_abonnement_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversiteFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.filiere')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.universite')),
            ],
            options={
                'verbose_name': 'Relation Université-Filière',
                'verbose_name_plural': 'Relations Université-Filières',
                'unique_together': {('universite', 'filiere')},
            },
        ),
        migrations.CreateModel(
            name='FilierePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.filiere')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.promotion')),
            ],
            options={
                'verbose_name': 'Relation Filière-Promotion',
                'verbose_name_plural': 'Relations Filières-Promotions',
                'unique_together': {('filiere', 'promotion')},
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='filieres', through='courses.FilierePromotion', to='courses.promotion'),
        ),
        migrations.AddField(
            model_name='universite',
            name='filieres',
            field=models.ManyToManyField(blank=True, related_name='universites', through='courses.UniversiteFiliere', to='courses.filiere'),
        ),
    ]
