# Generated by Django 4.2.7 on 2026-01-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_migrate_existing_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_transcription', models.TextField(help_text='Texte brut transcrit par Deepgram')),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('duree_audio', models.FloatField(default=0, help_text="Durée de l'audio en secondes")),
                ('confidence', models.FloatField(default=0, help_text='Score de confiance Deepgram (0-1)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='courses.session')),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='summary',
            name='transcription',
            field=models.ForeignKey(blank=True, help_text='Transcription source du résumé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='courses.transcription'),
        ),
    ]
