# Generated by Django 4.2.7 on 2026-01-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_transcription_summary_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='audio_duration',
            field=models.FloatField(default=0, help_text="Durée de l'audio en secondes"),
        ),
        migrations.AddField(
            model_name='session',
            name='error_message',
            field=models.TextField(blank=True, help_text="Message d'erreur en cas d'échec", null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Date de fin de traitement', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('transcribed', 'Transcrit'), ('summarized', 'Résumé disponible'), ('failed', 'Échec')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Date de soumission au traitement', null=True),
        ),
    ]
