# Generated by Django 4.2.7 on 2026-01-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_session_processing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='filiere_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.filiere'),
        ),
        migrations.AddField(
            model_name='course',
            name='promotion_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.promotion'),
        ),
        migrations.AddField(
            model_name='course',
            name='universite_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.universite'),
        ),
    ]
