# Generated by Django 4.2.7 on 2026-04-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_exercise_service_is_active_summary_is_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='summary_price',
            field=models.FloatField(default=0.0, help_text='Prix du résumé à générer'),
        ),
        migrations.AddField(
            model_name='session',
            name='summary_title',
            field=models.CharField(blank=True, default='', help_text='Titre du résumé à générer', max_length=200),
        ),
    ]
