# Generated by Django 4.2.7 on 2026-04-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_summary_title_price_to_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='professeur',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
