# Generated by Django 4.2.7 on 2026-05-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_professeurfilieres_alter_professeur_filieres'),
        ('courses', '0014_professeur_filieres_fix'),
    ]

    operations = [
    ]
