# Generated by Django 4.2.7 on 2026-06-11 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0017_universite_filieres_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professeurfilieres',
            options={'managed': False, 'verbose_name': 'Relation Professeur-Filière', 'verbose_name_plural': 'Relations Professeur-Filières'},
        ),
        migrations.CreateModel(
            name='UserPersonalizedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', help_text='Niveau de difficulté sélectionné', max_length=10)),
                ('questions', models.JSONField(default=list, help_text='Liste des 8 questions QCM au format JSON unique pour cet utilisateur')),
                ('seed', models.IntegerField(help_text='Seed aléatoire utilisée pour la génération (permet variation)')),
                ('regenerated_count', models.IntegerField(default=0, help_text="Nombre de fois que l'utilisateur a régénéré cet exercice")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('generating', 'Génération en cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.ForeignKey(help_text="Résumé source sur lequel est basé l'exercice", on_delete=django.db.models.deletion.CASCADE, related_name='personalized_exercises', to='courses.summary')),
                ('user', models.ForeignKey(help_text='Utilisateur propriétaire de cet exercice personnalisé', on_delete=django.db.models.deletion.CASCADE, related_name='personalized_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercice Personnalisé Utilisateur',
                'verbose_name_plural': 'Exercices Personnalisés Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPersonalizedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text="Réponses de l'utilisateur {index_question: 'A/B/C/D'}")),
                ('results_detail', models.JSONField(default=list, help_text='Détail de chaque question avec correction')),
                ('score', models.FloatField(default=0.0, help_text='Score en pourcentage (0-100)')),
                ('correct_answers_count', models.IntegerField(default=0, help_text='Nombre de bonnes réponses')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Temps passé en secondes')),
                ('personalized_exercise', models.ForeignKey(help_text='Exercice personnalisé concerné', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.userpersonalizedexercise')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a tenté (redondant mais pratique)', on_delete=django.db.models.deletion.CASCADE, related_name='personalized_exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tentative d'exercice personnalisé",
                'verbose_name_plural': "Tentatives d'exercices personnalisés",
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userpersonalizedexercise',
            index=models.Index(fields=['user', 'summary'], name='courses_use_user_id_b64b91_idx'),
        ),
        migrations.AddIndex(
            model_name='userpersonalizedexercise',
            index=models.Index(fields=['status'], name='courses_use_status_da3851_idx'),
        ),
        migrations.AddIndex(
            model_name='userpersonalizedexercise',
            index=models.Index(fields=['difficulty'], name='courses_use_difficu_a9c623_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpersonalizedexercise',
            unique_together={('user', 'summary')},
        ),
    ]
