# Generated by Django 4.2.7 on 2026-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_m2m_relations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpersonalizedexercise',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpersonalizedexercise',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='userpersonalizedexercise',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserPersonalizedAttempt',
        ),
        migrations.DeleteModel(
            name='UserPersonalizedExercise',
        ),
    ]
