# Generated by Django 4.2.7 on 2026-06-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_add_difficulty_to_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='courses.course')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='courses.filiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='courses.professeur')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='courses.promotion')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='courses.universite')),
            ],
            options={
                'verbose_name': 'Dispense',
                'verbose_name_plural': 'Dispenses',
                'ordering': ['-created_at'],
                'unique_together': {('cours', 'professeur', 'promotion')},
            },
        ),
    ]
