# Generated by Django 4.2.7 on 2026-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_exercise_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisequestion',
            name='code_block',
            field=models.TextField(blank=True, help_text='Contenu technique (code source, formule, algorithme, commande, pseudo-code)', null=True),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='code_language',
            field=models.CharField(blank=True, help_text='Langage ou type du contenu technique (python, latex, sql, formula, algorithm, etc.)', max_length=50, null=True),
        ),
    ]
