# Generated by Django 4.2.7 on 2026-08-11 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0025_alter_exercise_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userpersonalizedexercise',
            name='courses_use_user_id_b64b91_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userpersonalizedexercise',
            unique_together={('user', 'summary', 'difficulty')},
        ),
        migrations.AddIndex(
            model_name='userpersonalizedexercise',
            index=models.Index(fields=['user', 'summary', 'difficulty'], name='courses_use_user_id_e1c46e_idx'),
        ),
    ]
