# Generated by Django 4.2.7 on 2025-08-27 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('premium', 'Premium'), ('vip', 'VIP'), ('basic', 'Basic')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain'), ('EUR', 'Euro')], default='CDF', max_length=3)),
                ('duree_mois', models.IntegerField(help_text='Durée en mois')),
                ('features', models.JSONField(default=list, help_text='Liste des fonctionnalités')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('pending', 'En attente')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0, help_text='Progression en pourcentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='payments.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
    ]
