# Generated by Django 4.2.7 on 2026-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_service_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], default='CDF', max_length=3),
        ),
    ]
