# Generated by Django 4.2.7 on 2026-03-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_exercise_service_is_active_summary_is_validated_and_more'),
        ('payments', '0003_alter_purchase_payment_method_alter_service_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='courses.summary'),
        ),
    ]
