# Generated by Django 4.2.7 on 2025-08-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_filiere_promotion_universite'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='university',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groupe',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('CP', 'Chef de Promotion'), ('ADMIN', 'Administrateur')], default='ETUDIANT', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.promotion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='universite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.universite'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.filiere'),
        ),
    ]
