# Generated by Django 4.2.7 on 2026-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='groupe',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('CP', 'Chef de Promotion'), ('ADMIN', 'Administrateur'), ('Prof', 'Professeur')], default='ETUDIANT', max_length=20),
        ),
    ]
