# Generated by Django 4.2.7 on 2026-08-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_userprofile_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(blank=True, help_text='Motivation du candidat (pourquoi devenir CP)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, help_text="Commentaire de l'administrateur (approbation/refus)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='Utilisateur qui fait la demande', on_delete=django.db.models.deletion.CASCADE, related_name='cp_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande CP',
                'verbose_name_plural': 'Demandes CP',
                'ordering': ['-created_at'],
            },
        ),
    ]
