# Generated by Django 4.2.7 on 2026-08-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cp_onboarding_completed',
            field=models.BooleanField(default=True, help_text="Indique si le CP a terminé son parcours d'onboarding"),
        ),
    ]
