# Generated by Django 4.2.7 on 2026-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_cp_onboarding_default_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='cprequest',
            name='email',
            field=models.EmailField(blank=True, help_text="Email du candidat pour les notifications d'approbation/refus", max_length=254),
        ),
    ]
