# Generated by Django 4.2.7 on 2026-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cprequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
