# Generated by Django 4.2.7 on 2026-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cprequest',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Numéro de téléphone du candidat (prérempli depuis le profil, modifiable)', max_length=20),
        ),
    ]
